default: &default
  adapter: postgresql
  encoding: unicode
  database: rattvisekollen
  port: 5432
  encoding: utf8
  pool: 5

development:
  <<: *default

production:
  <<: *default
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOST"] %>
