development:
  adapter: postgresql
  encoding: unicode
  database: rattvisekollen_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rattvisekollen_test
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  database: rattvisekollen_staging
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: rattvisekollen_production
  pool: 5
